name: py36
channels:
  - conda-forge
dependencies:
  - python==3.6
  - pip
  - openssl
  - xz
  - setuptools
  - wheel
  - zlib
  - babel
  - docutils
  - freetype
  - imagesize
  - jbig
  - jinja2
  - jpeg
  - libpng
  - libtiff
  - markupsafe
  - mock
  - olefile
  - pbr
  - pillow
  - pygments
  - pytz
  - requests
  - six
  - snowballstemmer
  - sphinx
