name: py_test
channels:
  - anaconda
dependencies:
  - python>=3.5
  - pip
  - openssl
  - xz
  - setuptools
  - wheel
  - zlib
  - babel
  - docutils
  - freetype
  - imagesize
  - jbig
  - jinja2
  - jpeg
  - libpng
  - libtiff
  - markupsafe
  - mock
  - olefile
  - pbr
  - pillow
  - pygments
  - pytz
  - requests
  - six
  - snowballstemmer
  - sphinx
  - sphinx_rtd_theme
