name: py37
# channels:
#   - conda-forge
dependencies:
  - python=3.7
  - sphinx
  - sphinx_rtd_theme
  - pip
  - openssl
  - xz
  - setuptools
  - wheel
  - zlib
  - babel
  - docutils
  - freetype
  - imagesize
  - jbig
  - jinja2
  - jpeg
  - libpng
  - libtiff
  - markupsafe
  - mock
  - olefile
  - pbr
  - pillow
  - pygments
  - pytz
  - requests
  - six
  - snowballstemmer
  - sphinx
  - sqlite
  - xz
  - aiohttp
