name: py36
channels:
  - conda-forge
dependencies:
  - python=3.6
  - sphinx=1.5.3
  - sphinx_rtd_theme=0.2.4
  - pip
  - openssl
  - xz
  - setuptools
  - wheel
  - zlib
  - babel
  - docutils
  - freetype
  - imagesize
  - jbig
  - jinja2
  - jpeg
  - libpng
  - libtiff
  - markupsafe
  - mock
  - olefile
  - pbr
  - pillow
  - pygments
  - pytz
  - requests
  - six
  - snowballstemmer
  - sphinx
  - sqlite
  - xz
  - aiohttp
  - aioredis

