dependencies:
  - python=3.6.1
  - pip
  - setuptools
  - wheel
  - zlib
  - babel
  - docutils
  - freetype
  - imagesize
  - jbig
  - jinja2
  - jpeg
  - libpng
  - libtiff
  - markupsafe
  - mock
  - olefile
  - pbr
  - pillow
  - pygments
  - pytz
  - requests
  - six
  - snowballstemmer
  - sphinx
  - sphinx_rtd_theme
