name: Build docs

on:
  push:
    branches:
      - dev-3.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry==1.0
          poetry install
          mkdir -p reports

      - name: Lint code
        run: |
          make flake8-report
          make mypy-report

      - name: Run tests
        run: |
          make test-coverage

      - name: Build docs
        run: |
          make docs
          make docs-copy-reports

      - name: Build package
        run: |
          poetry build
          mkdir -p site/simple
          mv dist site/simple/aiogram

      - name: Publish docs
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: 2038.host
          FTP_USERNAME: ${{ secrets.DOCS_FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.DOCS_FTP_PASSWORD }}
          LOCAL_DIR: site
          REMOTE_DIR: public
          ARGS: --delete --parallel=20
